FROM arm64v8/debian:10-slim

LABEL maintainer="Wolfgang Gassler, Guillaume Lamirand"
LABEL description="XtraBackup based MySQL / MariaDB backup docker image to create incremental backups periodically"

# installing xtrabackup according to https://docs.percona.com/percona-xtrabackup/8.4/apt-repo.html

RUN . /etc/os-release \
    && apt-get update \
    && apt-get -y install wget lsb-release gnupg2 cron curl \
    && rm -rf /etc/cron.* \
    && . /etc/os-release \
    && wget https://repo.percona.com/apt/percona-release_latest.${VERSION_CODENAME}_all.deb \
    && dpkg -i percona-release_latest.${VERSION_CODENAME}_all.deb \
    && rm -f percona-release_latest.${VERSION_CODENAME}_all.deb \
    && percona-release enable-only tools release \
    && apt-get update \
    && apt-get -y install percona-xtrabackup-84=8.4.0-2.buster

COPY scripts /scripts

VOLUME /backup /var/lib/mysql
WORKDIR /backup

CMD ["/scripts/start.sh"]